spring:
  application:
    name: dsipilot-file-mover
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/dsipilot_batch?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    defer-datasource-initialization: true
  batch:
    job:
      enabled: false #disabled job run at startup
    jdbc:
      initialize-schema: never

logging:
  level:
    org.springframework.batch: INFO
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
